/**
 * Centralized, i18n-ready strings dictionary for the Clinical Diagnostic Radiography Suite.
 * All user-facing labels, prompts, tooltips, and status descriptions must be sourced here.
 */

export const STRINGS = {
  header: {
    telemetryServerLabel: "Neural Inference Gateway",
    pacsGatewayLabel: "PACS Gateway",
    pacsConnected: "Connected",
    auditLogsButton: "Audit Logs",
    uploadScanButton: "Upload New Scan",
    phiDeidentifiedBadge: "Safe Harbor De-identified",
    onlineStatus: "Online",
    offlineStatus: "Offline / Standby",
  },
  workflow: {
    title: "Clinical Protocol:",
    stage1Label: "1. Scan Ingestion",
    stage2Label: "2. Domain Routing",
    stage3Label: "3. Diagnostic Findings & Sign-Off",
    sessionPrefix: "Session",
    awaitingSession: "AWAITING SCAN INGESTION",
  },
  viewport: {
    title: "Scan Ingestion & Radiographic Viewport",
    subtitle: "Upload patient radiologic scan for real-time model analysis",
    replaceButton: "Replace",
    removeButton: "Remove Scan",
    dropzoneTitle: "Select or Drop Patient Radiograph",
    dropzonePrompt: "Click to select or drag and drop a medical image into this area.",
    supportedFormatsNotice: "DICOM (.dcm), PNG, JPEG, or TIFF up to 25MB. Zero sample presets pre-loaded.",
    chooseFileButton: "Choose Scan File",
    analyzingPrompt: "Executing Neural Inference Pipeline…",
    analyzingSubtext: "Evaluating anatomical domain routing & pathology classification",
    runDiagnostic: "Run Diagnostic Pipeline",
    reRunDiagnostic: "Re-run Diagnostic Pipeline",
    brightnessLabel: "Brightness",
    contrastLabel: "Contrast",
    invertLut: "Invert Grayscale LUT",
    toggleFullscreen: "Toggle Fullscreen",
    toggleAdjustments: "Image Adjustments",
    resetViewport: "Reset Viewport",
    toggleHeatmap: "Activation Heatmap (Grad-CAM)",
    heatmapActive: "Heatmap Overlay Active",
  },
  router: {
    title: "Anatomical Domain Routing",
    subtitle: "Automated classification of anatomical scan region",
    targetConcordance: "Anatomical Target Concordance",
    viewTechnicalDetails: "View Technical Pipeline Details",
    hideTechnicalDetails: "Hide Technical Pipeline Details",
    routedBadge: "CONFIRMED ROUTE",
    clickToOverride: "Click to route to this anatomical domain",
    awaitingTitle: "Awaiting Scan Analysis",
    awaitingSubtext: "Click \"Run Diagnostic Pipeline\" to classify anatomical domain",
    autonomousRoutingLabel: "Autonomous Domain Routing:",
    networkEngaged: "Target Pathology Network Engaged",
    standingBy: "Standing By",
  },
  diagnostic: {
    title: "Diagnostic Pathology Finding",
    subtitle: "Evaluated tissue pathology & risk classification",
    primaryFindingHeader: "Primary Radiologic Finding",
    confidenceHeader: "Confidence",
    differentialBreakdown: "Differential Diagnosis Breakdown",
    emptyStateTitle: "No Pathology Inferred",
    emptyStateSubtext: "Ingest a scan and execute analysis to view findings",
    lowConfidenceNotice: "Low Confidence Finding — Secondary Specialist Review Recommended",
    analysisLatency: "Analysis Latency:",
    pipelineTotalLatency: "Pipeline Total:",
    toggleHeatmapButton: "Grad-CAM Attention Map",
  },
  clinicalActions: {
    title: "Clinical Actions",
    caseReadyNotice: "Case Ready for Sign-Off",
    sendToPhysician: "Send to Attending Physician",
    patientPdfReport: "Patient PDF Report",
    exportFindings: "Export Findings (JSON)",
  },
  tabs: {
    findingsTabTitle: "Clinical Impression & Action Protocol",
    metadataTabTitle: "DICOM & Study Metadata",
    emptyFindingsTitle: "No Findings Inferred Yet",
    emptyFindingsPrompt: "Upload a radiographic scan and execute the diagnostic pipeline to view clinical impressions.",
    emptyMetadataTitle: "No Scan Ingested Yet",
    emptyMetadataPrompt: "Upload a radiographic scan to inspect preliminary image header tags and accession info.",
    demographicsSection: "Patient Demographics (DICOM Module 0010)",
    acquisitionSection: "Acquisition & Protocol Parameters (DICOM Module 0018)",
    preliminaryNotice: "Preliminary Ingestion Metadata (Extracted Prior to Inference)",
  },
  modals: {
    sendPhysician: {
      title: "Transmit to Attending Physician",
      subtitle: "EMR / PACS Clinical Notification Gateway",
      targetPhysicianLabel: "Select Attending Physician / Radiologist",
      priorityLabel: "Clinical Urgency / Triage Priority",
      notesLabel: "Clinical Notes & Impression Dispatch",
      cancelButton: "Cancel",
      sendButton: "Dispatch Notification",
      sendingButton: "Dispatching…",
      successNotice: "Case Successfully Dispatched to EMR Queue",
    },
    patientReport: {
      title: "Radiology Diagnostic Examination Report",
      printPdfButton: "Print / Save PDF",
      preliminaryWatermark: "PRELIMINARY REPORT — REQUIRES FINAL ATTENDING SIGNATURE",
      verifiedWatermark: "PATHOLOGY REPORT — COMPLETED",
      riskStratification: "Risk Stratification:",
      differentialTableClass: "Pathology Class",
      differentialTableProb: "Confidence Score",
      differentialTableTier: "Risk Tier",
    },
    auditLogs: {
      title: "Clinical Audit Trail & Access Log",
      subtitle: "Regulatory compliance log (21 CFR Part 11 & HIPAA Audit Standard)",
      tableId: "Event ID",
      tableTimestamp: "Timestamp",
      tableActor: "Actor / System",
      tableAction: "Action Event",
      tableDetails: "Audit Description",
      tableStatus: "Verification",
      exportCsv: "Export Audit Log (CSV)",
    },
  },
  footer: {
    modelVersionLabel: "Model Version:",
    lastValidatedLabel: "Last Validated:",
    regulatoryNotice: "Clinical Decision Support Software — For use by qualified clinicians only.",
  },
};
